### ISSUE TITLE
Automatic cert renewal

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-enote-letsencrypt#2]
You can test automatic renewal for your certificates by running this command:
```
./path/to/certbot-auto renew --dry-run 
```
If that appears to be working correctly, you can arrange for automatic renewal by adding a cron or systemd job which runs the following:
```
./path/to/certbot-auto renew --quiet --no-self-upgrade
```

https://certbot.eff.org/docs/using.html#renewal

**Comment by iainbryson** [comment]
IIRC, we already have this?  there's a cron job, etc..?

**Comment by dtu-compute** [comment]
Not yet it looks like:

https://github.com/dtu-compute/dtu-enote-installer/blob/devel/installer.sh#L114

So in a way I should have created the ticket in `dtu-enote-installer` =)

**Comment by iainbryson** [comment]
Ah, OK, so this is about having the installer set up the cron job for renewal? Like what we have going on in prod atm?

**Comment by dtu-compute** [comment]
`crontab -l` on production doesn't seam to have any renewals. Or there is perhaps a daily/weekly script?

But yes, the installer should set it up. The script is made so it can be run as many times as wanted without doing any damage.

It doesn't disable SELinux in `/etc/selinux/config`, but at some point we should enable it also in production. It just makes debugging harder outside the containers as one can get errors such as `File not found` even though it is there. One just doesn't have permission to see it.
