### ISSUE TITLE
make-certs.sh with argument only create one cert

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-enote-letsencrypt#3]
In relation to #2 would it be a good idea to modify `make-certs.sh` to not update certs, and have to specify as an argument exactly which cert to create?

For each course it is ~4 extra certs that are needed so we can quickly run into the letsencrypt limit of times pr day we can ask for certs during development if we continue to ask for all certs.

**Comment by iainbryson** [comment]
How about we:

keep `make-certs.sh` as a tool to bulk-create for new courses and during setup. We then modify it to only create certs, and no-op if a cert doesn't exist.

Create `make-cert.sh` which will create a single cert as you suggest above.

Create `update-certs.sh` as a tool to bulk update -- but not create -- the certs.

This separates things more cleanly.

Note that there's also now a way to create a self-signed cert using the rake task `setup:make_self_signed_certs`.  We need to have _some_ certs on initial startup or else the reverse proxy will die.  So setup would typically work by running this task, then when the proxy is up and running, execute `make-certs.sh` or `make-cert.sh` to generate real certs.

How does this sound?

**Comment by dtu-compute** [comment]
Excellent idea! Let's go for it =)
